export const SKILLS = {
    0: {
        name: "Woodcutting",
        media: "assets/media/skills/woodcutting/woodcutting.svg",
        hasMastery: true,
        maxLevel: 99,
    },
    1: {
        name: "Fishing",
        media: "assets/media/skills/fishing/fishing.svg",
        hasMastery: true,
        maxLevel: 99,
    },
    2: {
        name: "Firemaking",
        media: "assets/media/skills/firemaking/firemaking.svg",
        hasMastery: true,
        maxLevel: 99,
    },
    3: {
        name: "Cooking",
        media: "assets/media/skills/cooking/cooking.svg",
        hasMastery: true,
        maxLevel: 99,
    },
    4: {
        name: "Mining",
        media: "assets/media/skills/mining/mining.svg",
        hasMastery: true,
        maxLevel: 99,
    },
    5: {
        name: "Smithing",
        media: "assets/media/skills/smithing/smithing.svg",
        hasMastery: true,
        maxLevel: 99,
    },
    6: {
        name: "Attack",
        media: "assets/media/skills/attack/attack.svg",
        hasMastery: false,
        maxLevel: 99,
    },
    7: {
        name: "Strength",
        media: "assets/media/skills/strength/strength.svg",
        hasMastery: false,
        maxLevel: 99,
    },
    8: {
        name: "Defence",
        media: "assets/media/skills/defence/defence.svg",
        hasMastery: false,
        maxLevel: 99,
    },
    9: {
        name: "Hitpoints",
        media: "assets/media/skills/hitpoints/hitpoints.svg",
        hasMastery: false,
        maxLevel: 99,
    },
    10: {
        name: "Thieving",
        media: "assets/media/skills/thieving/thieving.svg",
        hasMastery: true,
        maxLevel: 99,
    },
    11: {
        name: "Farming",
        media: "assets/media/skills/farming/farming.svg",
        hasMastery: true,
        maxLevel: 99,
    },
    12: {
        name: "Ranged",
        media: "assets/media/skills/ranged/ranged.svg",
        hasMastery: false,
        maxLevel: 99,
    },
    13: {
        name: "Fletching",
        media: "assets/media/skills/fletching/fletching.svg",
        hasMastery: true,
        maxLevel: 99,
    },
    14: {
        name: "Crafting",
        media: "assets/media/skills/crafting/crafting.svg",
        hasMastery: true,
        maxLevel: 99,
    },
    15: {
        name: "Runecrafting",
        media: "assets/media/skills/runecrafting/runecrafting.svg",
        hasMastery: true,
        maxLevel: 99,
    },
    16: {
        name: "Magic",
        media: "assets/media/skills/magic/magic.svg",
        hasMastery: false,
        maxLevel: 99,
    },
    17: {
        name: "Prayer",
        media: "assets/media/skills/prayer/prayer.svg",
        hasMastery: false,
        maxLevel: 99,
    },
    18: {
        name: "Slayer",
        media: "assets/media/skills/slayer/slayer.svg",
        hasMastery: false,
        maxLevel: 99,
    },
    19: {
        name: "Herblore",
        media: "assets/media/skills/herblore/herblore.svg",
        hasMastery: true,
        maxLevel: 99,
    },
    20: {
        name: "Agility",
        media: "assets/media/skills/agility/agility.svg",
        hasMastery: true,
        maxLevel: 99,
    },
};